version: '3'

services:
  db:
     image: 'postgres'
     ports:
       - '5432'
     environment:
      - POSTGRES_DB=makeability
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
     volumes:
      - postgres-data:/var/lib/postgresql/data
  website:    
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '127.0.0.1:8571:8000'
    volumes:
      - .:/code
      - /cse/web/research/makelab/www:/code/media
    depends_on:
      - db
    command: ["./docker-entrypoint.sh", "db", "python", "manage.py"]
    links:
      - "db:database"
volumes:
    postgres-data:   
