version: '3'

services:
  db:
     image: 'postgres'
     ports:
       - '5432'
     environment:
      - POSTGRES_DB=makeability
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
     volumes:
      - /var/lib/postgresql/data
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - db
    command: ["./docker-entrypoint.sh", "db", "python", "manage.py"]
    links:
      - "db:db"    